# Generated by Django 2.2.3 on 2019-07-17 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turns_remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('total_points', models.IntegerField()),
                ('r1_points', models.IntegerField()),
                ('r2_points', models.IntegerField()),
                ('free_tokens', models.IntegerField()),
                ('current_turn', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=400)),
                ('answer_text', models.CharField(max_length=200)),
                ('point_value', models.IntegerField()),
                ('asked', models.BooleanField(default=False)),
                ('round_number', models.CharField(choices=[(1, 'One'), (2, 'Two')], max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_of_jeopardy.Category')),
                ('game_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wheel_of_jeopardy.GameSession')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='User1_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='wheel_of_jeopardy.User'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='User2_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='wheel_of_jeopardy.User'),
        ),
    ]
