# Generated by Django 2.1.4 on 2019-08-04 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_text', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_of_jeopardy.Category')),
                ('game_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wheel_of_jeopardy.GameSession')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('r1_points', models.IntegerField(verbose_name='round1 points')),
                ('r2_points', models.IntegerField()),
                ('free_tokens', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='User1_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='wheel_of_jeopardy.User'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='User2_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='wheel_of_jeopardy.User'),
        ),
    ]
