# Generated by Django 2.2.4 on 2019-08-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_of_jeopardy', '0002_gamewheel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_round',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='number_turns_left',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='current_turn',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
