# Generated by Django 2.2.4 on 2019-08-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_of_jeopardy', '0003_auto_20190807_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
