# Generated by Django 2.2.4 on 2019-08-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_of_jeopardy', '0004_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='round_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
